### ISSUE TITLE
System.err: a.a.a.a.a.ac 

### ISSUE THREAD

**Issue by NirujanSuresh** [spark/spark-sdk-android#13]
Hello,

I am using the cloudsdk and used gradle to import the dependency (io.particle:cloudsdk:0.3.4. What I'm trying to achieve is to login using the Particle cloud sdk, get a list of devices and communicate with them. When it is in debugging mode, everything works fine. In release, I added the oauth credentials inside the strings.xml file. I get the following message when I try to login:

W/System.err: a.a.a.a.a.ac
06-28 01:46:08.516 952-1030/? W/System.err: at a.a.a.a.a.y.a(Unknown Source)
06-28 01:46:08.516 952-1030/? W/System.err: at com.bmertech.activities.k.a(Unknown Source)
06-28 01:46:08.516 952-1030/? W/System.err: at com.bmertech.activities.k.doInBackground(Unknown Source)
06-28 01:46:08.516 952-1030/? W/System.err: at android.os.AsyncTask$2.call(AsyncTask.java:292)
06-28 01:46:08.516 952-1030/? W/System.err: at java.util.concurrent.FutureTask.run(FutureTask.java:237)
06-28 01:46:08.516 952-1030/? W/System.err: at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
06-28 01:46:08.517 952-1030/? W/System.err: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
06-28 01:46:08.517 952-1030/? W/System.err: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
06-28 01:46:08.517 952-1030/? W/System.err: at java.lang.Thread.run(Thread.java:818)

Thank you for your on-going support,
Nirujan

**Comment by jensck** [comment]
Without a de-obfuscated stack trace, I'm afraid I can't help you.  You'll need to do something like this: http://simplyadvanced.net/blog/android-how-to-decode-proguards-obfuscated-code-from-stack-trace/

**Comment by NirujanSuresh** [comment]
W/System.err: a.a.a.a.a.ac
at a.a.a.a.a.y.a(y.java)
06-28 01:46:08.516 952-1030/? W/System.err: at com.bmertech.activities.k.a(k.java)
06-28 01:46:08.516 952-1030/? W/System.err: at com.bmertech.activities.k.doInBackground(k.java)
06-28 01:46:08.516 952-1030/? W/System.err: at android.os.AsyncTask$2.call(AsyncTask.java:292)
06-28 01:46:08.516 952-1030/? W/System.err: at java.util.concurrent.FutureTask.run(FutureTask.java:237)
06-28 01:46:08.516 952-1030/? W/System.err: at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
06-28 01:46:08.517 952-1030/? W/System.err: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
06-28 01:46:08.517 952-1030/? W/System.err: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
06-28 01:46:08.517 952-1030/? W/System.err: at java.lang.Thread.run(Thread.java:818)

**Comment by jensck** [comment]
Looks like that's the same stack trace as above.  Can you make a release build with proguard disabled and try reproducing this?

**Comment by NirujanSuresh** [comment]
Looks like it worked without proguard? But do you know why that could be the case? Here are the rules I added to proguard:

-dontwarn okio.**
-dontwarn rx.**
-dontwarn sun.misc.**
-dontwarn com.google.appengine.api.**

**Comment by jensck** [comment]
Cool, glad to hear it's working without Pro Guard at least.

Try adding rules to keep io.particle.*\* and let me know how that goes. If that works, I will add that to our documentation!

**Comment by NirujanSuresh** [comment]
That worked for me. Thank you.

**Comment by jensck** [comment]
Brilliant, thanks for the update!
