### ISSUE TITLE
Unsubscribing from events not working

### ISSUE THREAD

**Issue by etix** [spark/spark-sdk-android#15]
Calling `unsubscribeFromEventWithID` with the ID given by `subscribeToEvents` doesn't really unsubscribe. Messages are not transmitted to the handler anymore but the connection to the cloud is kept as I can still see messages like those in the console:

`entering org.kaazing.net.sse.impl.AuthenticatedSseEventSourceImpl.messageReceived {"data":"mydata","ttl":"60","published_at":"2016-08-19T00:34:34.796Z","coreid":"xxxxx"}`

Of course doing some subscribe / unsubscribe sequences make the number of connections grow and there's no way to kill them and it hurts the battery.

**Comment by jensck** [comment]
Gah, battery life bugs!   I'll take a look this weekend. Thanks for the clear report!

**Comment by jensck** [comment]
OK, I think I've tracked this down.  I'll test the fix and do a release sometime this week.

**Comment by etix** [comment]
That's great. Thanks @jensck!

**Comment by SleepyTonic** [comment]
I also seen this issue and resolved it by calling `sseEventSource.close()` in `EventsDelegate.stopListening()`

**Comment by jensck** [comment]
Fixed in upcoming release
