### ISSUE TITLE
Project not compatible with latest version of Android Studio/Gradle

### ISSUE THREAD

**Issue by NozMaximus** [spark/spark-sdk-android#16]
The cloudsdk\build.gradle returns the following error when trying to load the project:
Plugin is too old, please update to a more recent version, or set ANDROID_DAILY_OVERRIDE environment variable to "ccbf255801ffbc86319e3fd14bdc0682272bf5c9".

**Comment by jensck** [comment]
Fixed. in master.  Thanks for the report!

**Comment by NozMaximus** [comment]
Hey Jens,

Thanks for getting on this so quickly.  Are you using the Android Studio
IDE, or just the command line gradle compiler?

Thanks
-Nozar

**Comment by jensck** [comment]
Android Studio, but shouldn't make any difference.  Are you still having trouble?

**Comment by NozMaximus** [comment]
Hi,

Yes I am.  I was making great progress updating the app and playing around
with it to understand what's going on until I decided to accept the recent
Android Studio update last week.

After I grabbed the updates you checked in, I still am getting the
following:

Gradle 'spark-sdk-android-master' project refresh failed.
    Error: No service of type Factory available in ProjectScopeServices.

When I try to clean the project to rebuild it I get the following:

Information:Gradle tasks [clean]
FAILURE: Build failed with an exception.
- What went wrong:
  A problem occurred evaluating script.
  > Failed to apply plugin [id 'com.github.dcendents.android-maven']
  > Could not create plugin of type 'AndroidMavenPlugin'.
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or
  --debug option to get more log output.
  Information:BUILD FAILED
  Information:Total time: 0.562 secs
  Error:FAILURE: Build failed with an exception.
- Where:
  Script 'C:\work2\spark-sdk-android-master\pom_generator_v1.gradle' line: 3
- What went wrong:
  A problem occurred evaluating script.
  
  > Failed to apply plugin [id 'com.github.dcendents.android-maven']
  > Could not create plugin of type 'AndroidMavenPlugin'.
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or
  --debug option to get more log output.

Information:1 error
Information:0 warnings
Information:See complete output in console

I regret doing this upgrade.  I should ignore all updates if I ever get
this working again :(

Thanks for the help.
-Nozar

**Comment by jensck** [comment]
@NozMaximus FWIW, AS upgrades aren't usually like this.  You'll experience much more pain from what you miss out on than the occasional pain you might get from upgrading.  That said, putting off upgrading until final, stable releases are out might be wise. :)

As for this specific issue, try uncommenting these lines in `build.gradle`:

```
apply from: '../pom_generator_v1.gradle'
apply from: '../bintray_upload_v1.gradle'
```

**Comment by NozMaximus** [comment]
They're not commented out at the moment.

Thanks
-Nozar

**Comment by jensck** [comment]
@NozMaximus better yet, try pulling for master one more time, it looks like upgrading some gradle plugins fixed this properly.  Let me know if you have any further trouble!

**Comment by NozMaximus** [comment]
Awesome!  Made it much further.  Compile completed.  Now it had trouble
making the apk:

:example_app:transformClassesWithDexForDebug FAILED
Error:Execution failed for task
':example_app:transformClassesWithDexForDebug'.

> com.android.build.api.transform.TransformException:
> com.android.ide.common.process.ProcessException:
> java.util.concurrent.ExecutionException: com.android.dex.DexException:
> Multiple dex files define
> Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;
> Information:BUILD FAILED
> Information:Total time: 6.255 secs
> Information:1 error
> Information:0 warnings

**Comment by NozMaximus** [comment]
Thank you for all the help.

Regards
-Nozar

**Comment by jensck** [comment]
Wow, I'm really on a roll with the incremental fixes tonight. ;)  Thanks for sticking with this and providing the quick feedback.

The example app is updated now, too.  I think, I hope, that should be the last of it...

**Comment by NozMaximus** [comment]
Hey,

Thanks for all the help.  Had some down time because I had to move.  But
back at it now.  I can't seem to get the .apk generated.  So confused now.
I can run my app in the simulator.  Launches ok.  But can't get the apk
generated.  The popup is there to "show in explorer", but there is no .apk
in the output folder.

Any advice is appreciated.

Thanks
-Nozar
