### ISSUE TITLE
How to receive more than one variable in the async task?

### ISSUE THREAD

**Issue by izmevid** [spark/spark-sdk-android#17]
Hello,

I am currently working on the issue of not knowing how to get multiple variable out of one async task function.

I would be very happy about an example code showing how to do that because the example app currently only shows how to get one variable at a time. 

That make it clear I am not that experienced in Android Studio or Java but I however did not find an answer to my issue.

Thanks

**Comment by jensck** [comment]
Answered on the original forum post: http://community.particle.io/t/android-sdk-how-to-receive-more-than-one-variable-in-async-task/26415/2?u=jensck
