### ISSUE TITLE
homescreen widget development

### ISSUE THREAD

**Issue by bfiegel** [spark/spark-sdk-android#2]
I don't see a clean way of developing a flexible app alongside a homescreen widget.  Am I missing something?

**Comment by jensck** [comment]
I don't believe there's anything about the Cloud SDK which would prevent one from creating a homescreen widget in one's app.  Was there something in particular you ran into, some roadblock or something specific that's missing?

**Comment by jensck** [comment]
Closing this for now.  @bfiegel if you can provide the info requested, please feel free to re-open!
