### ISSUE TITLE
ETA on Subscribing to Device Events

### ISSUE THREAD

**Issue by HauptmannEck** [spark/spark-sdk-android#3]
I am just curious if there is a known date that subscribing to device events will be added.

Thanks

**Comment by towynlin** [comment]
Thanks @HauptmannEck. We have no estimated date for the addition of an events system right now but it's on our short list.

**Comment by yeti7** [comment]
Gentle nudge in the same direction here. Are we talking days or weeks?

**Comment by jensck** [comment]
I'd put the ETA at about a week, two at the most.

**Comment by idokleinman** [comment]
I'll also make an announcement in our mobile community website once this feature is published.

**Comment by jensck** [comment]
Update: this is very close to complete, but needs a little more testing before it ships.

I'm at the Android Dev Summit today(!), but I should be able to release in the next couple days, in time for the community to do some Thanksgiving break Particle hacking with the events API! :)

**Comment by jensck** [comment]
Update: ran into some issues prior to release, but this feature is imminent, and getting it out is my very top priority right now.

**Comment by HauptmannEck** [comment]
very nice, thanks

**Comment by jensck** [comment]
Huzzah, it's released!  Grab version `0.3.0` of the Android SDK and join in on the event love!

I know this one took a lot longer than anticipated; thanks to everyone for their patience on this.

**Comment by fcordeg** [comment]
Hi! Is it possible to have an updated example that shows how to login to the cloud? Unfortunately the code is still out-of-date at https://docs.particle.io/photon/android/.

Many thanks in advance!
Kind Regards

**Comment by jensck** [comment]
@fcordeg I'm working to update the docs site today, actually.  For an answer _right now_ though, the README.md files for the SDK and device setup libs have current docs:
https://github.com/spark/spark-sdk-android/blob/master/README.md
https://github.com/spark/spark-setup-android/blob/master/README.md
