### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by idokleinman** [spark/spark-sdk-android#30]
- Unit
- Integration
- Acceptance

Open for discussion on tools and approach
cc @jensck

**Comment by jensck** [comment]
My only thoughts on this (largely echoed from our previous conversations on the subject):

I would recommend de-prioritizing tests on the SDK in favor of high level integration tests on the device setup lib.  By far the most common source of issues has been with the setup process running on new versions of Android, and it's also one of the more time consuming things to test when you have to run that test many, many times by hand.

As for implementation, I'd probably stick with JUnit-driven unit tests and Espresso-driven integration tests.  Maybe try out Spek or Spock for unit tests if you really want something more concise?  And I'd _avoid_ both PowerMock, and any cross-platform testing framework.  Both are devil's bargains: they look great up front, but they come with nasty side effects and limitations you'll only discover after using them for a bit that eclipse their value.

**Comment by idokleinman** [comment]
I agree that high level integration tests on device setup lib are important, but actually are less likely to change/break (pending Android API changes/devices behaviour). Also - would be pretty hard to implement. Another piece on info: 
We will soon push for a integrated "browserified" soft AP process that should work similarly on iOS and Android webviews. 

Lately an API response change caused a crash in the iOS app which could have been caught easily with unit tests on SDK - the API IS changing all the time and might cause breakage. Just my 0.02$ on why unit tests on SDK still have lots of value.

**Comment by jason1813** [comment]
Question. Does anyone know where the repo is for the Particle Photon that goes along with the example_app in this repository? Sorry I wasn't sure where else to put this.
