### ISSUE TITLE
Local spark and android API

### ISSUE THREAD

**Issue by maxdd** [spark/spark-sdk-android#43]
As the title is saying, is it possible to redirect the API to our own cloud server?

**Comment by CityVibes** [comment]
@maxdd As far as I know - no. You can change base url [here](https://github.com/spark/spark-sdk-android/blob/master/cloudsdk/src/main/res/values/config.xml) to direct calls to your api instead (if it supports those calls) and make your own build of cloud sdk.

**Comment by maxdd** [comment]
Isn't it enough? If i set up my on build of https://github.com/spark/spark-server and make it reachable from outside wouldn't it be enough?

**Comment by idokleinman** [comment]
Hi @maxdd this is a relatively active fork of the Particle API (aka Spark server):
https://github.com/Brewskey/spark-server

you can run it on your server and point mobile app API url to there.
Remember `spark-server` has a  limited feature set and is not by any means a complete clone of the full Particle API, also it is not meant for scaling, just for experimenting/development/prototyping.

Good luck!
