### ISSUE TITLE
Async RejectedExecutionException

### ISSUE THREAD

**Issue by CityVibes** [spark/spark-sdk-android#50]
Cloud SDK `Async` implementation occasionally throws `RejectedExecutionException` (once ThreadPoolExecutor limit is exceeded). This exception was also a culprit behind few crashes on Tinker app.

Few options put forward by @jensck:

- Use our own ThreadPoolExecutor with a higher limit
    - Overload `executeAsync()` allowing developers to specify `ThreadPoolExecutor` limits.
    - Add global mutable state `Async.setExecutor()` 

Once either option is implemented following has to be considered:

- Check/catch `RejectedExecutionException` in all overloaded `executeAsync()` methods.
- Execute `executeAsync()` call without throwing a `ParticleCloudException` (perhaps we should return a boolean response indicating wether task was added to a queue).

**Comment by jensck** [comment]
Moved: https://github.com/particle-iot/particle-android/issues/63
