### ISSUE TITLE
ParticleDevice.subscribeToEvents doesn't include access_token in Uri

### ISSUE THREAD

**Issue by reddigfabian** [spark/spark-sdk-android#7]
This is in reference to [this](https://community.particle.io/t/particle-sdk-for-android-not-subscribing-to-events/19126) open topic on the particle community forums.

After digging through some of the cloud sdk's source code and understanding a portion of it, it seems that the sdk does not include the ParticleCloud instance's current access token as a parameter in the Uri that is passed to the EventReader.

I cloned the repo and made enough changes to get the uri that gets output to the log in subscribeToEventWithUri to function in a browser.

However the ParticleEventHandler I've implemented in my app still isn't receiving events.

**Comment by jensck** [comment]
**Note:** I'm going to continue the conversation around this bug over on [that community post](https://community.particle.io/t/particle-sdk-for-android-not-subscribing-to-events), since that's where the bulk of the info is, and (seemingly) where the community prefers to discuss these things.

**Comment by jensck** [comment]
Fixed by #8
